---
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files:
            - "helm/Chart.yaml"
          from: 'version: ".*"'
          to: 'version: "${nextRelease.version}"'
  - - "@semantic-release/git"
    - assets:
        - "helm/Chart.yaml"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/gitlab"
branches:
  - "main"
tagFormat:
  - "${version}"
