---
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/gitlab"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files:
            - helm/Chart.yaml
          from: 'version: ".*"'
          to: 'version: "${nextRelease.version}"'
          results:
            - file: helm/Chart.yaml
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  - - "@semantic-release/git"
    - assets:
        - config/.workflow.*
      message: "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
branches:
  - "main"
tagFormat:
  - "${version}"
