apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}-sa
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: UPS_NAME
              value: {{ .Values.scale_controller.ups_name | quote }}
            - name: NS_SCALE_STATUS
              value: {{ .Values.scale_controller.ns_scale_status | quote }}
            - name: NS_SCALE_NAME
              value: {{ .Values.scale_controller.ns_scale_name | quote }}
            - name: SCALE_JOB_NAME
              value: {{ .Values.scale_controller.scale_job_name | quote }}
            - name: SCALE_JOB_SA_NAME
              value: {{ .Values.scale_controller.scale_job_sa_name | quote }}
            - name: SCALE_JOB_IMAGE
              value: {{ .Values.scale_controller.scale_job_image | quote }}
            - name: DISCORD_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-scale-controller
                  key: discord-channel
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-scale-controller
                  key: discord-token
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
