apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: scalestatuses.spirit-dev.net
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: spirit-dev.net
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                status:
                  type: string
                  nullable: true
                transition:
                  type: string
                  nullable: true
                sequence:
                  type: string
                  nullable: true
                last_transition:
                  type: string
                  format: date-time
                duration:
                  type: string
                  nullable: true
                objects:
                  type: array
                  items:
                    type: object
                    properties:
                      sequence:
                        type: string
                        nullable: true
                      type:
                        type: string
                        nullable: true
                      namespace:
                        type: string
                        nullable: true
                      name:
                        type: string
                        nullable: true
                ups_status:
                  type: string

      additionalPrinterColumns:
        - name: Status
          type: string
          description: Cluster scaling status
          jsonPath: .spec.status
        - name: Transition
          type: string
          description: Cluster scaling transition
          jsonPath: .spec.transition
        - name: Last transition
          type: date
          description: Last transition date
          jsonPath: .spec.last_transition

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: scalestatuses
    # singular name to be used as an alias on the CLI and for display
    singular: scalestatus
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ScaleStatus
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - scales
